---
title: "Data Tidying"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(dplyr)
library(tidyr)
library(readr)
```

# Read in data

Data come from [Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2.] (https://knb.ecoinformatics.org/view/df35b.304.2)

```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", show_col_types = FALSE)

```

# Clean and reshape data

Drop notes and all column
```{r}
catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
 

catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", "1", Chinook)) %>% 
  mutate(Chinook = as.integer(Chinook))


catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), names_to = "species", values_to = "catch")%>% 
  rename(catch_thousands = catch) %>% 
  mutate(catch = catch_thousands * 1000)%>% 
  select(-catch_thousands)


mean_region <- catch_long %>% 
  group_by(Region) %>%
  summarise(catch_mean = mean(catch))


catch_original %>% 
  group_by(Year) %>% 
  summarise(n = n())

```


# Join to regions dataset

```{r}
region_defs <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1") %>% 
  select(code, mgmtArea)

```

```{r}

catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))

```

