---
title: "Data Vis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(scales)
```

```{r}

data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv"),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"))
        return(esc)
    }
)

head(esc)
```

Calculate annual escapement by species and region
```{r}

annual_esc <- esc %>% 
  separate(sampleDate, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Pink", "Coho", "Chum"))%>%
  group_by(Species, SASAP.Region, year) %>% 
  summarise(escapement = sum(DailyCount))

```


```{r}
ggplot(annual_esc, mapping = aes(x = Species, y = escapement)) +
  geom_col(fill = "blue")

```

# Leaflet maps

```{r}

locs <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r}
leaflet(locs) %>% 
  addTiles() %>%  # adds a basemap
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~Location)
```

