---
title: "Practice Data Tidying"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
```

```{r}
webpage <- read_html("https://www.pwrc.usgs.gov/bbl/manual/speclist.cfm")

tbls <- html_nodes(webpage, "table") %>% 
    html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))
```

```{r}
pred <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d")
nest <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e")

```

```{r}

# test_nest <- left_join(nest, species, by = c("species" = "alpha_code"))
# test_pred <- left_join(pred, species, by = c("species" = "alpha_code"))

make_common_names <- function(df1, df2) {
  birds <- left_join(df1, df2, by = c("species" = "alpha_code"))
  return(birds)
  
}

tot_pred <-  make_common_names(pred, species) %>% 
 group_by(year, species) %>%
  summarise(pred_counts = sum(n()))
  
colnames(tot_pred)

ggplot(tot_pred, mapping = aes(x = year, y = pred_counts, color = species)) +
  geom_line()
  
```



